baseURL: "https://lewisajones.com/"
title: Lewis A. Jones
languageCode: en-us
theme: hugo-theme-hello-friend-ng
PygmentsCodeFences: yes
PygmentsStyle: monokai
paginate: 10
rssLimit: 10
copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License.
archetypeDir: archetypes
contentDir: content
dataDir: data
layoutDir: layouts
publishDir: public
buildDrafts: no
buildFuture: no
buildExpired: no
canonifyURLs: yes
enableRobotsTXT: yes
enableGitInfo: no
enableEmoji: yes
enableMissingTranslationPlaceholders: no
disableRSS: no
disableSitemap: no
disable404: no
disableHugoGeneratorInject: no
permalinks:
  posts: /posts/:year/:month/:title/
author:
  name: Lewis A. Jones
blackfriday:
  hrefTargetBlank: yes
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  customCSS: []
  customJS: []
  dateform: Jan 2, 2006
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04
  dateformShort: Jan 2
  description: Palaeobiology, Macroecology and R Programming
  disableReadOtherPosts: no
  enableGlobalLanguageMenu: no
  enableSharingButtons: yes
  enableThemeToggle: yes
  favicon:
    color:
      mask: '#1b1c1d'
      msapplication: '#1b1c1d'
      theme: '#1b1c1d'
  footer:
    author: yes
    bottomText:
      - Powered by <a href="http://gohugo.io">Hugo</a>
      - Base theme from <a href="https://github.com/rhazdon">Djordje Atlialp</a>
      - Modified by <a href="https://github.com/LewisAJones">Lewis A. Jones</a/>
    copyright: yes
    rss: no
    topText: []
    trademark: yes
  homeSubtitle:
      - Palaeobiology,
      - Macroecology,
      - R Programming
  images: ''
  justifyContent: yes
  keywords: 'Palaeobiology, Macroecology and R Programming'
  logo:
    logoHomeLink: /
    logoMark: '>'
    logoText: Hello, world!
    logoCursorColor: "#199885"
  social:
    - name: twitter
      url: https://twitter.com/LewisAlanJones
    - name: email
      url: mailto:LewisAlan.Jones@uvigo.es
    - name: googlescholar
      url: https://scholar.google.com/citations?user=X0AvsOkAAAAJ&hl=en&authuser=1
    - name: researchgate
      url: https://www.researchgate.net/profile/Lewis-Jones-11
    - name: github
      url: https://github.com/LewisAJones
    - name: linkedin
      url: https://www.linkedin.com/in/lewisajones/
languages:
  en:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
      rel="noopener">CC BY-NC 4.0</a>
    subtitle: Palaeobiology & Macroecology
    weight: 1
  es:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
      rel="noopener">CC BY-NC 4.0</a>
    subtitle: Hola
    weight: 2
menu:
  main:
    - identifier: about
      name: About
      url: about/
      weight: 1
    - identifier: experience
      name: Experience
      url: experience/
      weight: 2
    - identifier: publications
      name: Publications
      url: publications/
      weight: 3
    - identifier: software
      name: Software
      url: software/
      weight: 4
    - identifier: gallery
      name: Gallery
      url: gallery/
      weight: 5
