---
title: "Publications"
author: "Lewis A. Jones"
date: 2022-05-07
---
## **Peer-reviewed publications**

1. **Lewis A. Jones**, Philip D. Mannion, Alexander Farnsworth, Fran Bragg, Daniel J. Lunt (2022). [Climatic and tectonic drivers shaped the tropical distribution of coral reefs.](https://www.nature.com/articles/s41467-022-30793-8) *Nature Communications*. 13 (3120), 1--10. [View graphical abstract.](NatComms-GA.jpg)</p>

1. **Lewis A. Jones** and Kilian Eichenseer (2022). [Uneven spatial sampling distorts reconstructions of Phanerozoic seawater temperature.](https://pubs.geoscienceworld.org/gsa/geology/article/doi/10.1130/G49132.1/609542/Uneven-spatial-sampling-distorts-reconstructions) *Geology* 50 (2), 238--242. [View graphical abstract.](https://pbs.twimg.com/media/FDyMbOZXIAYX2rp?format=jpg&name=4096x4096)

1. **Lewis A. Jones**, Christopher D. Dean, Philip D. Mannion, Alexander Farnsworth, Peter A. Allison (2021). [Spatial sampling heterogeneity limits the detectability of deep time latitudinal biodiversity gradients.](https://royalsocietypublishing.org/doi/10.1098/rspb.2020.2762)  *Proceedings of the Royal Society B* 288 (1945), 20202762. [View graphical abstract.](https://pbs.twimg.com/media/Eu-0pYiXUAEGG_A?format=jpg&name=4096x4096)

1. **Lewis A. Jones**, Philip D. Mannion, Alexander Farnsworth, Paul Valdes, Sarah-Jane Kelland, and Peter A. Allison (2019). [Coupling of palaeontological and neontological reef coral data improves forecasts of biodiversity responses under global climatic change.](https://royalsocietypublishing.org/doi/10.1098/rsos.182111) *Royal Society Open Science* 6 (4), 182111.

1. Alfio Alessandro Chiarenza, Philip D. Mannion, Daniel Lunt, Alexander Farnsworth, **Lewis A. Jones**, Sarah-Jane Kelland, and Peter A. Allison (2019). [Ecological niche modelling does not support climatically-driven dinosaur diversity decline before the Cretaceous/Paleogene mass extinction.](https://www.nature.com/articles/s41467-019-08997-2) *Nature Communications* 10 (1091), 1--14.[View graphical abstract.](NatCommsDino-GA.jpg)</p>

## **Theses**

1. **Lewis A. Jones**. (2020). On the detectability of latitudinal biodiversity gradients in deep time. PhD Thesis. Imperial College London. *Supervisors: Dr Philip D. Mannion and Prof. Peter A. Allison*.

1. **Lewis A. Jones**. (2015). The end-Triassic mass extinction. An investigation of the British geological record: testing for the role of volcanism and ocean anoxia. Master's Thesis. *Supervisor: Dr David Bond*. 

## **Other works**

1. Michael C. A. Stevens, Yiqiao Chen, Alex Stringer, Caitlin Clemmow, and **Lewis A. Jones** (2020). [Key factors driving obesity in the UK](http://london.gisruk.org/gisruk2020_proceedings/GISRUK2020_paper_17.pdf). *Geographic Information System Research UK*.

1. **Lewis A. Jones** (2020). [Meeting report: 13th International Symposium of Fossil Cnidaria and Porifera](https://www.palass.org/sites/default/files/media/publications/newsletters/number_102/number_102.pdf). *The Palaeontological Association Newsletter 102*.

