---
title: "Curriculum Vitae"
author: "Lewis A. Jones"
date: 2022-05-10
---
<p align="center">
**Lewis A. Jones**
<br>
Postdoctoral Research Fellow
<br>
Vigo, Spain
<br>
<span style="color: #ed4d7e;">[LewisAlan.Jones@uvigo.es](mailto:LewisAlan.Jones@uvigo.es)</span>
</p>

### <span style="color: #ed4d7e;">Education </span>
**PhD in Earth Sciences** (2016--2020)
<br>
Imperial College London, London, UK
<br>
Research advisors: Dr Philip D. Mannion & Prof. Peter A. Allison
<br>
Thesis title: On the detectability of the latitudinal biodiversity gradient in deep time  
<br>
**MPhysGeog in Physical Geography** (2011--2015)
<br>
University of Hull, Hull, UK
<br>
Research advisor: Prof. David P.G. Bond
<br>
Thesis title: The End-Triassic mass extinction. An investigation of the British Geological Record: testing for the role of volcanism and ocean anoxia
<br>  
**CMI (Level 5) in Management and Leadership** (2012--2015)
<br>
Leeds University Officer Training Corps, Leeds, UK  

### <span style="color: #ed4d7e;">Employment </span>

**Postdoctoral Research Fellow (Juan de la Cierva)** (2023--current)
<br>
Mapas Lab, Centro de Investigación Mariña, Universidade de Vigo, Vigo, Spain  
<br>
**Postdoctoral Research Fellow (European Research Council)** (2021--2022)
<br>
Mapas Lab, Centro de Investigación Mariña, Universidade de Vigo, Vigo, Spain  
<br>
**Graduate Teaching Assistant** (2016--2021)
<br>
Department of Earth Science and Engineering, Imperial College London, London, UK  
<br>
**Student Hall's Warden** (2016--2021)
<br>
Woodward Buildings, Imperial College London, London, UK  
<br>
**British Army Officer Cadet** (2012--2015)
<br>
Leeds University Officer Training Corps, Leeds, UK  
<br>
**Sales Assistant** (2010--2012)
<br>
Republic Ltd, Grimsby and Hull, UK  
<br>
**Baker** (2008--2010)
<br>
Muffin Break, Grimsby, UK

### <span style="color: #ed4d7e;">Research focus </span>
- Macroecology and biodiversity
- Fossil record bias
- Corals and reef ecosystems
- Palaeoclimate
- R programming


### <span style="color: #ed4d7e;">Publications </span>

#### **Peer-reviewed publications**

1. <p align="justify">**Lewis A. Jones**, Philip D. Mannion, Alexander Farnsworth, Fran Bragg, Daniel J. Lunt (2022). [Climatic and tectonic drivers shaped the tropical distribution of coral reefs](https://www.nature.com/articles/s41467-022-30793-8). *Nature Communications* 13 (3120), 1--10. [View graphical abstract.](NatComms-GA.jpg)</p>

1. <p align="justify">**Lewis A. Jones** and Kilian Eichenseer (2022). [Uneven spatial sampling distorts reconstructions of Phanerozoic seawater temperature.](https://pubs.geoscienceworld.org/gsa/geology/article/doi/10.1130/G49132.1/609542/Uneven-spatial-sampling-distorts-reconstructions) *Geology* 50 (2), 238--242. [View graphical abstract.](Geology-GA.jpg)</p>

1. <p align="justify">**Lewis A. Jones**, Christopher D. Dean, Philip D. Mannion, Alexander Farnsworth, Peter A. Allison (2021). [Spatial sampling heterogeneity limits the detectability of deep time latitudinal biodiversity gradients.](https://royalsocietypublishing.org/doi/10.1098/rspb.2020.2762)  *Proceedings of the Royal Society B* 288 (1945), 20202762. [View graphical abstract.](ProcB-GA.jpg)</p>

1. <p align="justify">**Lewis A. Jones**, Philip D. Mannion, Alexander Farnsworth, Paul Valdes, Sarah-Jane Kelland, and Peter A. Allison (2019). [Coupling of palaeontological and neontological reef coral data improves forecasts of biodiversity responses under global climatic change.](https://royalsocietypublishing.org/doi/10.1098/rsos.182111) *Royal Society Open Science* 6 (4), 182111. [View graphical abstract.](RoySoc-GA.jpg)</p>

1. <p align="justify">Alfio Alessandro Chiarenza, Philip D. Mannion, Daniel Lunt, Alexander Farnsworth, **Lewis A. Jones**, Sarah-Jane Kelland, and Peter A. Allison (2019). [Ecological niche modelling does not support climatically-driven dinosaur diversity decline before the Cretaceous/Paleogene mass extinction.](https://www.nature.com/articles/s41467-019-08997-2) *Nature Communications* 10 (1091), 1--14. [View graphical abstract.](NatCommsDino-GA.jpg)</p>

#### **Theses**

1. <p align="justify">**Lewis A. Jones** (2020). On the detectability of latitudinal biodiversity gradients in deep time. PhD Thesis. Imperial College London. *Supervisors: Dr Philip D. Mannion and Prof. Peter A. Allison*.</p>

1. <p align="justify">**Lewis A. Jones** (2015). The end-Triassic mass extinction. An investigation of the British geological record: testing for the role of volcanism and ocean anoxia. Master Thesis. *Supervisor: Dr David Bond*. </p>

#### **Other works**

1. <p align="justify">**Lewis A. Jones**, William Gearty, Bethany J. Allen, Kilian Eichenseer, Christopher D. Dean, Sofía Galván, Miranta Kouvari, Pedro L. Godoy, Cecily Nicholl, Lucas Buffan, Erin M. Dillon, Joseph T. Flannery-Sutherland and A. Alessandro Chiarenza (2022). [palaeoverse:a community-driven R package to support palaeobiological analyses](https://eartharxiv.org/repository/view/4619/). *EarthArXiv*.</p>

1. <p align="justify">**Lewis A. Jones** (2022). [Book review: Timefulness: How thinking like a geologist can help save the world](https://www.palass.org/sites/default/files/media/publications/newsletters/number_110/PAN110.pdf). *The Palaeontological Association Newsletter 110*.</p>

1. <p align="justify">Michael Stevens, Yiqiao Chen, Alex Stringer, Caitlin Clemmow, and **Lewis A. Jones** (2020). [Key factors driving obesity in the UK](http://london.gisruk.org/gisruk2020_proceedings/GISRUK2020_paper_17.pdf). *GISRUK*. </p>

1. <p align="justify">**Lewis A. Jones** (2020). [Meeting report: 13th International Symposium of Fossil Cnidaria and Porifera](https://www.palass.org/sites/default/files/media/publications/newsletters/number_102/number_102.pdf). *The Palaeontological Association Newsletter 102*.</p>


### <span style="color: #ed4d7e;">Academic awards and grants</span>
**R for Palaeobiologists: Workshop and Hackathon** (2022)
<br>
Grant-in-Aid from The Palaeontological Association, UK
<br>
Value: 2000 GBP
<br>  
**CASA team hackathon award** (2019)
<br>
Centre for Advanced Spatial Analysis, University College London, London
<br>
Value: 250 GBP
<br>  
**Travel grant award** (2019)
<br>
Palaeontological Association
<br>
Value: 220 EUR  
<br>
**President's PhD Scholarship** (2016)
<br>
Imperial College London, London, UK
<br>
Value: 70,000 GBP  
<br>
**Roger Ward thesis award** (2015)
<br>
University of Hull, Hull, UK
<br>

### <span style="color: #ed4d7e;">Invited presentations</span>

<p align="justify">**PalaeoSIG (British Ecological Society): Masterclass in R** (2022)
<br>
Talk: Into the palaeoverse: a community-driven R package
<br>
<p align="justify">**Getech PLC** (2018)
<br>
Talk: Ecological modelling in Geosciences
<br>

### <span style="color: #ed4d7e;">Selected conference presentations</span>

<p align="justify">**The Palaeontological Association: Annual Meeting** (2022)
<br>
Poster: Niche characterisation is biased by limited and heterogeneous spatial sampling
</p>
<p align="justify">**Simposio de Paleontologia del noroeste peninsular** (2022)
<br>
Poster: palaeoverse: a community-driven R package
</p>
<p align="justify">**The Palaeontological Association: Annual Meeting** (2019)
<br>
Talk: Poor spatial sampling coverage obscures our understanding of the latitudinal biodiversity gradient in deep time
<br>
Poster: Uneven spatial sampling in Phanerozoic palaeoclimate curves
</p>
<p align="justify">**13th International Symposium on Fossil Cnidaria and Porifera** (2019)
<br>
Talk: The evolution of the latitudinal biodiversity gradient in zooxanthellate corals</p>

<p align="justify">**The past is a foreign country: how much can the fossil record actually inform conservation?** (2019) 
<br>
Poster: Looking through the palaeontological window: reducing geographical and environmental bias in forecasting biodiversity responses</p>

<p align="justify">**Crossing the Palaeontological–Ecological Gap** (2018)
<br>
Talk: Absence of evidence is not evidence of absence: quantifying reef coral range shifts under global climatic change</p>

<p align="justify">**BES Macroecology** (2018)
<br>
Talk: Anthropogenic climate change and transitional distribution ranges of reef corals: insights from the last Pleistocene interglacial</p>

<p align="justify">**The Palaeontological Association: Annual Meeting** (2017)
<br>
Poster: Ecological niche modelling in deep time: constraining the transitional distribution ranges of reef corals</p>

<p align="justify"> **European Coral Reef Symposium** (2017)
<br>
Poster: Anthropogenic climate change and transitional distribution ranges of reef corals: insights from the last Pleistocene interglacial</p>


### <span style="color: #ed4d7e;">Fieldwork experience </span>

**León, Spain** (2022)
<br>
Logging and bulk sampling of Devonian sequences  
<br>
**Colorado and New Mexico, USA** (2016)
<br>
Logging, sampling, and fossil prospecting across the Cenomanian/Turonian boundary  
<br>
**Somerset, Lyme Regis, and Newark, UK** (2015)
<br>
Logging, sampling, and geochemical analysis across the Triassic/Jurassic boundary  
<br>
**Koh Rong, Cambodia** (2012)
<br>
Marine biological surveys as part of Koh Rong's (Cambodia) coral reef monitoring project

### <span style="color: #ed4d7e;">Professional development </span>

**Macroevolution and Phylogenies** (2022)
<br>
Transmitting Science, Online

**Data manipulation and Statistical Analysis in Palaeoecology** (2021)
<br>
Palaeoecology Group, British Ecological Society, Online

**Doctoral Summer School for Advanced Spatial Modelling** (2019)
<br>
The Centre for Advanced Spatial Analysis, University College London, London, UK
<br>  
**Species distribution modelling: fundamentals and the future workshop** (2019)
<br>
University of Nottingham, Nottingham, UK  
<br>
**Advanced ecological niche modelling** (2018)
<br>
University of Porto, Porto, Portugal  
<br>
**Introduction to ecological niche modelling** (2017)
<br>
Transmitting Science, Barcelona, Spain  
<br>
**Introduction to coral identification** (2017)
<br>
European Coral Reef Symposium, Oxford, UK  
<br>
**Introduction to larval dispersal modelling** (2017)
<br>
European Coral Reef Symposium, Oxford, UK

### <span style="color: #ed4d7e;">Student supervision </span>

**Miranta Kouvari** (2019--current)
<br>
University College London, London, UK
<br>
PhD project: The latitudinal biodiversity gradient of South American eutherians

**Lucas Buffan** (2021--2022)
<br>
University of Vigo, Vigo, Spain
<br>
Master's project: Spatial discrepancies in palaeogeographic reconstructions

### <span style="color: #ed4d7e;">Teaching and pastoral care </span>

**Graduate Teaching Assistant** (2016--2021)
<br>
Imperial College London, London, UK

- Palaeobiology I
- Palaeobiology II
- Dorset (UK) geology field course
- Almería (Spain) geology field course


**Student Hall's Warden** (2016--2021)
<br>
Woodward Buildings, Imperial College London, London, UK
<br>

### <span style="color: #ed4d7e;">Professional service and outreach</span>

**IFCRS Early Career Researcher Representative** (2021--current)
<br>
Committee member of the International Fossil Coral and Reef Society (IFCRS)
<br>  

**IFCRS Lecture Series** (2022)
<br>
International Fossil Coral and Reef Society, Online
<br>
Co-organised and ran a lecture series on fossil corals and reefs

**IFCRS Early Career Researcher Symposium** (2021)
<br>
International Fossil Coral and Reef Society, Online
<br>
Co-organised and ran an early career researcher meeting on fossil corals and reefs

**Fossil Fact or Fiction stall** (2019)
<br>
Einstein's Garden, Green Man Festival, Brecon Beacons, Wales
<br>
Co-ran a stall on fossil record bias over the course of the festival, find out more [here!](https://www.palass.org/sites/default/files/media/publications/newsletters/number_103/number_103.pdf)  
<br>
**Ecological niche modelling workshop** (2018)
<br>
Imperial College London, London, UK
<br>
Co-organised and ran a workshop on ecological niche modelling  
<br>
**Palaeontological Association meeting** (2017)
<br>
Imperial College London, London, UK
<br>
Co-organised and ran the annual meeting of the Palaeontological Association
<br>  

### <span style="color: #ed4d7e;">Peer-review experience</span>
*Science Advances*
<br>
*Nature Communications* 
<br>
*Scientific Reports*
<br>
*Ecological Monographs*

### <span style="color: #ed4d7e;">Skills </span>
**R programming**
<br>
Advanced proficiency in data analysis, data visualization, writing functions and packages
<br>  
**Geocomputation**
<br>
Proficient in spatial analysis and the use of R spatial packages (e.g. raster, terra, sf, sp)
<br>  
**Languages**
<br>
Spanish (CEFR B1)
<br>
Mandarin Chinese (HSK1)
<br>  
**SCUBA diver**
<br>
BSAC-accredited Ocean and Sports Diver
<br>  
**First-Aid**
<br>
Emergency first-aid at work & automated external defibrillator
<br>
Outdoors emergency first-aid
<br>
Mental health first-aid
<br>
Active-bystander
<br>  
**Driving**
<br>
Full UK driving license

### <span style="color: #ed4d7e;">Memberships </span>
Member of the International Fossil Coral and Reef Society (2018–present)
<br>
Member of the Palaeontological Association (2017–present)
<br>
Member of the Conservation Paleobiology Network (2019–present)
<br>
Member of the British Ecological Society (2017–present)





