---
title: "Curriculum Vitae"
author: "Lewis A. Jones"
date: 2022-05-10
---
<p align="center">
**Lewis A. Jones**
<br>
Postdoctoral Research Fellow
<br>
Vigo, Spain
<br>
<span style="color: #ed4d7e;">[LewisAlan.Jones@uvigo.es](mailto:LewisAlan.Jones@uvigo.es)</span>
</p>

### Education
**PhD in Earth Sciences** (2016--2020)
<br>
Imperial College London, London, UK
<br>
Research advisors: Dr Philip D. Mannion & Prof. Peter A. Allison
<br>
Thesis title: On the detectability of the latitudinal biodiversity gradient in deep time  
<br>
**MPhysGeog in Physical Geography** (2011--2015)
<br>
University of Hull, Hull, UK
<br>
Research advisors: Prof. David P.G. Bond
<br>
Thesis title: The End-Triassic mass extinction. An investigation of the British Geological Record: Testing for the role of volcanism and ocean anoxia.
<br>  
**CMI (Level 5) in Management and Leadership** (2012--2015)
<br>
Leeds University Officer Training Corps, Leeds, UK


### Employment

### Research focus

### Publications

### Academic awards and grants

### Selected conference presentations

### Fieldwork research experience

### Professional development

### Student supervision

### Teaching and pastoral care

### Professional service and outreach

### Skills

### Memberships



